---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: ep-os
description: This is my personal OS image.

base-image: quay.io/fedora/fedora-kinoite
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      nonfree: rpmfusion

    replace:
      - from-repo: rpmfusion
        packages:
          - old: mesa-va-drivers
            new: mesa-va-drivers-freeworld

    replace:
      - from-repo: rpmfusion
        allow-erasing: true
        packages:
          - old: ffmpeg-free
            new: ffmpeg

    install:
      packages:
        - neovim
        - python3-neovim
        - python3-pip
        - zsh
        - tmux
        - distrobox
        - cockpit
        - cockpit-files
        - cockpit-machines
        - cockpit-networkmanager
        - cockpit-ostree
        - cockpit-podman
        - cockpit-selinux
        - cockpit-storaged
        - minicom
        - bmon
        - pavucontrol-qt
        - intel-media-driver
        - libva-intel-driver
        - snapper
        - btrbk
        - rsnapshot
        - virt-manager
        - virt-viewer
        - syncthing
        - git
        - qt5ct
        - qt6ct
        - papirus-icon-theme
        - sysstat
        - lm_sensors
        - keepassxc
        - copyq
        - libva-utils
        - rclone
        - hyprland
        - waybar
        - wofi
        - dunst
        - swaybg
        - chromium
        - kitty
        - firefox
        - mozilla-ublock-origin
        - zathura
        - zathura-plugins-all
        - htop
        - python3-devel
        - helix
        - broadcom-wl
        - mkvtoolnix
        - mpv
        - skopeo
        - htop
        - telnet
        - rsync
        - iperf3
        - alsa-sof-firmware
        - wget
        - curl
        - sshfs
        - nodejs-bash-language-server
        - openvswitch
        - NetworkManager-ovs
    remove:
      packages:
        - toolbox

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans

  - type: default-flatpaks
    configurations:
      - notify: true 
        scope: system
        install: 
          - tv.kodi.Kodi
          - com.rustdesk.RustDesk
          - com.vscodium.codium
          - fr.handbrake.ghb
          - io.github.martchus.syncthingtray
          - org.fedoraproject.MediaWriter
          - org.gtk.Gtk3theme.Breeze
          - org.kde.kamoso
          - com.anydesk.Anydesk
          - org.kde.isoimagewriter
          - org.onlyoffice.desktopeditors
          - org.qbittorrent.qBittorrent
          - org.videolan.VLC
          - com.brave.Browser

  - type: chezmoi
    repository: "http://localhost/dotfiles" # my dotfiles repo
    all-users: false # make users have to enable chezmoi manually
    file-conflict-policy: replace # override changed files with those from the repo

  - type: script
    snippets:
      # Install ntfy.sh
      - "wget https://github.com/binwiederhier/ntfy/releases/download/v2.14.0/ntfy_2.14.0_linux_amd64.tar.gz -O /tmp/ntfy_2.14.0_linux_amd64.tar.gz"
      - "tar -xzf ntfy_2.14.0_linux_amd64.tar.gz -C /tmp"
      - "cp -a /tmp/ntfy_2.14.0_linux_amd64/ntfy /usr/bin/"
      - "mkdir /etc/ntfy && cp /tmp/ntfy_2.14.0_linux_amd64/client/*.yml /etc/ntfy"
      - "mkdir /etc/ntfy && cp /tmp/ntfy_2.14.0_linux_amd64/server/*.yml /etc/ntfy"
      - "rm -fr /tmp/ntfy_2.14.0_linux_amd64*"
      # Install application title bar plasmoid
      - "wget https://github.com/antroids/application-title-bar/releases/latest/download/application-title-bar.plasmoid -O /tmp/application-title-bar.plasmoid"
      - "kpackagetool6 -t Plasma/Applet -g -i /tmp/application-title-bar.plasmoid"
      - "rm /tmp/application-title-bar.plasmoid"

  - type: systemd
    system:
      enabled:
        - lm_sensors
        - sshd
        - cockpit.socket
        - sysstat
        - tuned
        - fstrim.timer
        - podman.socket
        - podman-auto-update.timer
        - cockpit.socket
        - libvirtd.socket

  - type: signing 
